#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
const root=process.cwd(), freeze=path.join(root,"runs/phase9_h5c/freeze"), gen=path.join(root,"runs/phase9_h5c/generation/validated");
const outDir=path.join(root,"outputs/phase9_h5c"), outPath=path.join(outDir,"phase9_h5c_claim_review_60_DRAFT.xlsx");
const jsonl=async p=>(await fs.readFile(p,"utf8")).trim().split(/\n/).filter(Boolean).map(JSON.parse);
const plans=await jsonl(path.join(freeze,"request_plan.jsonl")); const payloads=new Map((await jsonl(path.join(freeze,"request_payloads.jsonl"))).map(x=>[x.blinded_request_id,x]));
let generated=new Map(); try { for(const f of await fs.readdir(gen)){ const x=JSON.parse(await fs.readFile(path.join(gen,f),"utf8")); generated.set(x.blinded_request_id,x.answer); } } catch {}
const rows=plans.map((p,i)=>{ const ctx=JSON.parse(payloads.get(p.blinded_request_id).request.messages[0].content), a=generated.get(p.blinded_request_id); return {slot:`H5C${String(i+1).padStart(3,"0")}`,status:a?"READY_FROZEN":"PENDING_GENERATION",blind:p.blinded_request_id,question:ctx.question,e1:ctx.evidence[0]?.text||"",e2:ctx.evidence[1]?.text||"",e3:ctx.evidence[2]?.text||"",answer:a?.answer||"",abstained:a?.abstained??"",reason:a?.abstention_reason||"",cites:(a?.cited_evidence_ids||[]).join(",")}; });
const wb=Workbook.create(); const ins=wb.worksheets.add("Instructions"), a=wb.worksheets.add("Reviewer A"), b=wb.worksheets.add("Reviewer B"), adj=wb.worksheets.add("Adjudication"); for(const s of [ins,a,b,adj]) s.showGridLines=false;
ins.getRange("A1:B1").merge(); ins.getRange("A1").values=[["H5c Controlled Evidence Review — 60 Responses"]]; ins.getRange("A1:B1").format={fill:"#16324F",font:{bold:true,color:"#FFFFFF",size:16},rowHeight:32};
const notes=[["Status",generated.size===60?"READY_FROZEN — reviewers may score independently.":`DRAFT — ${generated.size}/60 generated. Do not score until all rows show READY_FROZEN.`],["Blinding","Condition and question mapping omitted from reviewer sheets."],["Claim scoring","Split externally verifiable claims. Score fully, partially, unsupported, or contradicted against supplied evidence only."],["Faithfulness","(fully supported + 0.5 × partially supported) / total claims."],["Abstention","Zero claims allowed only when model_abstained=TRUE."],["Adjudication","Required when total claims differ or reviewer ratios differ by >0.10."],["Confirmatory rule","Do not unseal condition mapping until review and adjudication validation pass."]]; ins.getRange(`A3:B${notes.length+2}`).values=notes; ins.getRange(`A3:A${notes.length+2}`).format={fill:"#D9EAF7",font:{bold:true,color:"#16324F"},verticalAlignment:"top"}; ins.getRange(`B3:B${notes.length+2}`).format={wrapText:true,verticalAlignment:"top"}; ins.getRange("A:A").format.columnWidth=22; ins.getRange("B:B").format.columnWidth=95;
const h=["answer_slot_id","protected_status","blinded_request_id","question","evidence_E01","evidence_E02","evidence_E03","generated_answer","model_abstained","model_abstention_reason","cited_evidence_ids","reviewer_id","total_verifiable_claims","fully_supported_claims","partially_supported_claims","unsupported_claims","contradicted_claims","faithfulness_ratio","review_status","reviewer_notes"];
const prot=rows.map(r=>[r.slot,r.status,r.blind,r.question,r.e1,r.e2,r.e3,r.answer,r.abstained,r.reason,r.cites]);
function reviewer(s,id){ s.getRange("A1:T1").values=[h]; s.getRange("A1:T1").format={fill:"#16324F",font:{bold:true,color:"#FFFFFF"},wrapText:true,rowHeight:34}; s.getRange("A2:K61").values=prot; s.getRange("L2:L61").values=rows.map(()=>[id]); s.getRange("M2:Q61").values=rows.map(()=>[null,null,null,null,null]); s.getRange("R2").formulas=[["=IF(M2>0,(N2+0.5*O2)/M2,\"\")"]]; s.getRange("R2:R61").fillDown(); s.getRange("S2:S61").values=rows.map(()=>["NOT_STARTED"]); s.getRange("T2:T61").values=rows.map(()=>[""]); s.freezePanes.freezeRows(1); s.freezePanes.freezeColumns(3); s.getRange("A2:K61").format={fill:"#F3F6F8",wrapText:true,verticalAlignment:"top",rowHeight:90}; s.getRange("L2:T61").format={fill:"#FFF8E1",wrapText:true,verticalAlignment:"top",rowHeight:90}; s.getRange("M2:Q61").dataValidation={rule:{type:"whole",operator:"between",formula1:0,formula2:100}}; s.getRange("S2:S61").dataValidation={rule:{type:"list",values:["NOT_STARTED","IN_PROGRESS","COMPLETE","NO_VERIFIABLE_CLAIMS"]}}; s.getRange("R2:R61").format.numberFormat="0.000"; [13,20,22,34,42,42,42,42,12,28,18,14,12,12,12,12,12,14,18,30].forEach((w,i)=>s.getRangeByIndexes(0,i,61,1).format.columnWidth=w); }
reviewer(a,"REVIEWER_A"); reviewer(b,"REVIEWER_B");
const ah=["answer_slot_id","protected_status","blinded_request_id","reviewer_A_ratio","reviewer_B_ratio","absolute_difference","adjudication_required","final_total_claims","final_fully_supported","final_partially_supported","final_unsupported","final_contradicted","final_faithfulness_ratio","adjudicator_id","adjudication_status","adjudication_notes"]; adj.getRange("A1:P1").values=[ah]; adj.getRange("A1:P1").format={fill:"#16324F",font:{bold:true,color:"#FFFFFF"},wrapText:true,rowHeight:34}; adj.getRange("A2:C61").values=rows.map(r=>[r.slot,r.status,r.blind]); adj.getRange("D2").formulas=[["='Reviewer A'!R2"]]; adj.getRange("D2:D61").fillDown(); adj.getRange("E2").formulas=[["='Reviewer B'!R2"]]; adj.getRange("E2:E61").fillDown(); adj.getRange("F2").formulas=[["=IF(AND(D2<>\"\",E2<>\"\"),ABS(D2-E2),\"\")"]]; adj.getRange("F2:F61").fillDown(); adj.getRange("G2").formulas=[["=IF(OR('Reviewer A'!M2<>'Reviewer B'!M2,F2>0.1),\"YES\",\"NO\")"]]; adj.getRange("G2:G61").fillDown(); adj.getRange("H2:L61").values=rows.map(()=>[null,null,null,null,null]); adj.getRange("M2").formulas=[["=IF(H2>0,(I2+0.5*J2)/H2,\"\")"]]; adj.getRange("M2:M61").fillDown(); adj.getRange("N2:P61").values=rows.map(()=>["","PENDING",""]); adj.getRange("H2:L61").dataValidation={rule:{type:"whole",operator:"between",formula1:0,formula2:100}}; adj.getRange("O2:O61").dataValidation={rule:{type:"list",values:["PENDING","COMPLETE","NO_VERIFIABLE_CLAIMS","NOT_REQUIRED"]}}; adj.getRange("A2:G61").format={fill:"#F3F6F8",wrapText:true}; adj.getRange("H2:P61").format={fill:"#FFF8E1",wrapText:true}; adj.freezePanes.freezeRows(1); adj.freezePanes.freezeColumns(3); [13,20,22,14,14,14,18,14,14,14,14,14,16,16,18,32].forEach((w,i)=>adj.getRangeByIndexes(0,i,61,1).format.columnWidth=w);
await fs.mkdir(outDir,{recursive:true}); for(const [name,range,file] of [["Instructions","A1:B9","instructions"],["Reviewer A","A1:T7","reviewer_a"],["Reviewer B","A1:T7","reviewer_b"],["Adjudication","A1:P8","adjudication"]]){ const img=await wb.render({sheetName:name,range,scale:.9,format:"png"}); await fs.writeFile(path.join(outDir,`${file}.png`),new Uint8Array(await img.arrayBuffer())); }
const inspect=await wb.inspect({kind:"table",sheetId:"Reviewer A",range:"A1:T5",include:"values,formulas",tableMaxRows:5,tableMaxCols:20}); await fs.writeFile(path.join(outDir,"inspect.ndjson"),inspect.ndjson); const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:300},summary:"formula error scan"}); await fs.writeFile(path.join(outDir,"formula_errors.ndjson"),errors.ndjson); const x=await SpreadsheetFile.exportXlsx(wb); await x.save(outPath); console.log(outPath);
